### ISSUE TITLE
Workflow 'build' fails

### ISSUE THREAD

**Issue by Builditluc** [maxam2017/productive-box#33]
At the 'commit change&push' stage, the build fails.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/37375448/113752074-dc846d00-970c-11eb-8442-95eb96f1fcdb.png">

At first, I thought my timezone is not correct but even the default one doesn't work

**Comment by fmaillet24** [comment]
Same issue, how did you resolve it plz ?

**Comment by Builditluc** [comment]
I didn't resolve the workflow error. I've just waited 24h and then it worked

**Comment by maxam2017** [comment]
Workflow fails due to no changes in builded code if you only change workflow config.

This issue has been fixed yesterday.
Pull the latest code in master branch would solve this problem 🙏
