### ISSUE TITLE
Workflow build fails

### ISSUE THREAD

**Issue by fmaillet24** [maxam2017/productive-box#34]
Hello, my workflow return :
```
Run git config user.name 'github-actions[bot]'
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Error: Process completed with exit code 1.
```

Does anyone have the same issue ?

**Comment by jonathangiamp** [comment]
Hi!

I found the solution, you've to add `--allow-empty` flag to the commit command (l.29) in `build.yml` file.
Hope that will help you!

**Comment by maxam2017** [comment]
@jonathangiamp thanks you for your suggestion.
This issue has already been fixed in https://github.com/maxam2017/productive-box/commit/f0889299b97b6f5e25b2f21a041c2508c88631ec
