### ISSUE TITLE
"Update gist" fails with "HttpError: Not Found"

### ISSUE THREAD

**Issue by thomasmerz** [maxam2017/productive-box#50]
Details can be found here:
https://github.com/thomasmerz/productive-box/runs/5074139692?check_suite_focus=true#logs
> Run maxam2017/productive-box@master
  env:
    GH_TOKEN: ***
    GIST_ID: 3b6ecf2621f492632018912a61025276
    TIMEZONE: Europe/Berlin
(node:1587) UnhandledPromiseRejectionWarning: HttpError: Not Found
    at /home/runner/work/_actions/maxam2017/productive-box/master/dist/index.js:1:78960
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1587) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1587) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

@maxam2017 - Please advice what I'm doing wrong or how to fix this. Thanks a lot 👍🏻

**Comment by thomasmerz** [comment]
@maxam2017 , can you please have a look at my issue and give some feedback? Thanks a lot.

**Comment by maxam2017** [comment]
your gist file seems to be working well now. Let me close this issue. Thanks
