### ISSUE TITLE
merge failed

### ISSUE THREAD

**Issue by NadudAn** [maxam2017/productive-box#77]
![image](https://user-images.githubusercontent.com/84761609/209130087-4ead4eb6-84f1-44f7-b890-f3d3553dedeb.png)
![image](https://user-images.githubusercontent.com/84761609/209132119-b891baf8-e68c-4a25-83a3-d73a6ddd4f0b.png)
![image](https://user-images.githubusercontent.com/84761609/209131374-c68c20b1-c8ed-4df8-ba98-0bcf93ddc03f.png)

https://github.com/NadudAn/productive-box/actions/runs/3452244558
https://github.com/NadudAn/productive-box/actions/runs/3745343956
https://github.com/NadudAn/productive-box/actions/runs/3753886002/jobs/6377580252

After merging recent commits, github action is failed.

What's wrong with my repository??
I need a solution.

**Comment by maxam2017** [comment]
I guess there is something wrong with your GitHub token (secret > GH_TOKEN).
make sure you set up `https://github.com/{YOUR USERNAME}/productive-box/settings/secrets/actions` correctly.

<img width="861" alt="截圖 2022-12-23 上午3 12 47" src="https://user-images.githubusercontent.com/25841814/209209509-61f26255-1121-4f1d-a263-d649405bb6a6.png">


and don't forget `repo` scope for this GitHub token is required.

**Comment by NadudAn** [comment]
Thank you,  I solved it. My Token had expired.
