### ISSUE TITLE
Still Node 12 used by referencing old "peter-evans/repository-dispatch@v1"

### ISSUE THREAD

**Issue by thomasmerz** [maxam2017/productive-box#78]
You're still using and old version of `peter-evans/repository-dispatch@v1` which still uses Node 12. Please update this to [v2](https://github.com/peter-evans/repository-dispatch/releases/tag/v2.0.0), too.

_Originally posted by @thomasmerz in https://github.com/maxam2017/productive-box/issues/75#issuecomment-1363820734_

**Comment by maxam2017** [comment]
Hi, 
This issue has already been solved in #70. (released in version v1.1.3)
If you are still experiencing this issue, please update your forked repository 🙏
