### ISSUE TITLE
my gist is not updated

### ISSUE THREAD

**Issue by skqoaudgh** [maxam2017/productive-box#8]
My  gist is not updated though i got success message for updating gist. 

i got github token with 'repo' and 'gist'. is it right? or  should i need other options? 

my repo url is [here](https://github.com/skqoaudgh/productive-box)

![image](https://user-images.githubusercontent.com/10339017/81323347-35e4b600-90d0-11ea-8eb3-8db12639afa0.png)

![image](https://user-images.githubusercontent.com/10339017/81323503-76443400-90d0-11ea-8770-9eee8ba080e3.png)

**Comment by maxam2017** [comment]
make sure your secret "GH_TOKEN" has been set (as below)

<img width="1125" alt="secret setting" src="https://user-images.githubusercontent.com/25841814/81324085-07171180-90c9-11ea-8e44-1ba2651b611a.png">

**Comment by skqoaudgh** [comment]
I set it up like that. but it’s still not working 8^8

what should i check to fix this?

**Comment by maxam2017** [comment]
ummm....  I just guess your locale is a typo

`LOCALE: ko_KR` 👉  `LOCALE: ko-KR`

**Comment by ianikpark** [comment]
Hi there, I'm experiencing the same issue as @skqoaudgh. I've tried debugging the code but am having no luck thus far. Any updates or suggestions on how to fix the problem would be very much appreciated.

**Comment by wooogi123** [comment]
Good day. I check code and find issue. ```Date().toLocaleTimeString('ko-KR', { hour12: false });``` has return timestamp to korean format like ```8시 0분 50초```.  I suggest set timezone, like ```('en-US', { hour12: false, timeZone: 'Asia/Seoul' })```

**Comment by skqoaudgh** [comment]
i re-wirte locate to 'en-US' but still not working.. 8^8

**Comment by wooogi123** [comment]
If you're not contributed other owner's repository, code will not writed anything.

**Comment by skqoaudgh** [comment]
you mean, the gist  is not writed if i commit to my public repo?

**Comment by wooogi123** [comment]
If my think is correct, yes
