### ISSUE TITLE
Hello, I have a failure with update gist

### ISSUE THREAD

**Issue by superbunny38** [maxam2017/productive-box#91]
Hello, I am facing a problem with updating gist, and I attach the screenshot with the failure message below.
I was using your early-bird tracking forked from https://github.com/techinpark/productive-box.
I will look forward to receiving advice on how I could solve this problem!

Thank you.
![image](https://github.com/maxam2017/productive-box/assets/48243487/d5c50572-4e76-4813-824f-c0518d794a45)

**Comment by CircleYoo** [comment]
Hi, please check if the token has expired.
Because I've been through it..

**Comment by maxam2017** [comment]
I apologize for the delayed response. 
Unfortunately, your action log is no longer available, so I couldn't identify the issue you encountered. 
If you come across this problem again, please reopen this issue with the error log, and I'll be happy to help you figure it out.
